# Generated by Django 3.2.20 on 2023-09-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_b8rx6z', upload_to='images/'),
        ),
    ]
